require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/*"
Metrics/AbcSize:
  Max: 40
  Exclude:
    - "db/migrate/*"
Layout/LineLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
